### ISSUE TITLE
Feature request: show coordinate 

### ISSUE THREAD

**Issue by ghost** [xrnoz/bedrock-server#1]
Hard to find where the minecraft console is.

**Comment by Yzen90** [comment]
I'm not sure what the request is. These are just some Linux bash scripts to manage bedrock server. Once you connect to the server you can input commands in-game if you enabled cheats.

**Comment by ghost** [comment]
Enable coordinate is still available even cheat is not enabled. It is part of the server setting.

**Comment by Yzen90** [comment]
I could not find that setting. You can download the server [distribution](https://www.minecraft.net/en-us/download/server/bedrock) and extract the files, there is no setting to enable coordinates mentioned on the `server.properties` or `bedrock_server_how_to.html` files.

As an example this [guide](https://shockbyte.com/billing/knowledgebase/201/How-to-Enable-Coordinates-on-Your-Minecraft-Bedrock-Server.html) instructs to enable cheats first and then enable coordinates. You can enable cheats on the server and then you can enable coordinates in-game.

If there is an undocumented setting for coordinates can you point to it?

**Comment by Yzen90** [comment]
If you really want to use the minecraft console on the server, you can stop the service (if enabled) and then run the server manually with `./run/<instance name>/bedrock_server.sh` and that way input console commands. I will look into inputting console commands to the systemd service.

**Comment by ghost** [comment]
That is helpful, thanks.
